# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import classification_report
import joblib

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [2]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced]

df = pd.read_csv("data_clustering_inverse.csv")

In [3]:
# Tampilkan 5 baris pertama dengan function head
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,amount_category,Target
0,1.0,CASH_IN,93413.63,C263588219,9071.00,102484.63,C1620301064,3284.00,0.0,0.0,0.0,tinggi,0
1,1.0,DEBIT,3179.70,C1182311147,124703.85,121524.14,C1540270363,20767.00,0.0,0.0,0.0,rendah,1
2,1.0,DEBIT,3111.86,C548795052,64665.82,61553.96,C240650537,10070.22,0.0,0.0,0.0,rendah,0
3,1.0,PAYMENT,8716.47,C215759534,8236.00,0.00,M2129844134,0.00,0.0,0.0,0.0,tinggi,2
4,1.0,PAYMENT,4189.31,C978035840,124618.50,120429.20,M666312528,0.00,0.0,0.0,0.0,sedang,0

In [4]:
#Ini bagian One Hot Encoding untuk fitur kategorikal.
#Yang diisi adalah dataframe df dan kolom categorical_cols.
categorical_cols = list(df.select_dtypes(include=['object']).columns)

# Gunakan 'pd.get_dummies' untuk melakukan OneHotEncoding
df_encoded = pd.get_dummies(
    df,
    columns = categorical_cols,
    drop_first = True
)

# Tampilkan 5 baris pertama untuk memverifikasi hasilnya
df_encoded.head()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,Target,type_DEBIT,...,nameDest_M949389138,nameDest_M964416619,nameDest_M964661854,nameDest_M971324399,nameDest_M975001918,nameDest_M980533504,nameDest_M982054651,nameDest_M993208674,amount_category_sedang,amount_category_tinggi
0,1.0,93413.63,9071.00,102484.63,3284.00,0.0,0.0,0.0,0,False,...,False,False,False,False,False,False,False,False,False,True
1,1.0,3179.70,124703.85,121524.14,20767.00,0.0,0.0,0.0,1,True,...,False,False,False,False,False,False,False,False,False,False
2,1.0,3111.86,64665.82,61553.96,10070.22,0.0,0.0,0.0,0,True,...,False,False,False,False,False,False,False,False,False,False
3,1.0,8716.47,8236.00,0.00,0.00,0.0,0.0,0.0,2,False,...,False,False,False,False,False,False,False,False,False,True
4,1.0,4189.31,124618.50,120429.20,0.00,0.0,0.0,0.0,0,False,...,False,False,False,False,False,False,False,False,True,False

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [5]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.

# Buat 'X' dengan menghapus 'Target' dari 'df_encoded' dan gunakan 'axis=1' untuk menandakan drop kolom.
X = df_encoded.drop('Target', axis=1)

# Buat 'y' dengan HANYA memilih kolom 'Target'.
y = df_encoded['Target']

# Panggil fungsi untuk membagi data.
#  - Gunakan 'stratify=y' agar proporsi kelas di train/test set sama.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42,
    stratify = y
)

print("Jumlah data total: ",len(X))
print("Jumlah data latih: ",len(X_train))
print("Jumlah data test: ",len(X_test))

Jumlah data total:  227
Jumlah data latih:  181
Jumlah data test:  46

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [6]:
# 1. Buat (instantiate) objek model Decision Tree
#    Gunakan 'random_state=42' agar hasilnya konsisten
decision_tree_model = DecisionTreeClassifier(random_state=42)

# 2. Latih (fit) model dengan data training (X_train dan y_train)
decision_tree_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [7]:
# Menyimpan Model

joblib.dump(decision_tree_model, 'decision_tree_model.h5')

['decision_tree_model.h5']

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**

In [9]:
# Melatih model menggunakan algoritma klasifikasi scikit-learn selain Decision Tree. (Contoh: RandomForestClassifier)

# Buat (instantiate) objek model baru
new_model = RandomForestClassifier(random_state=42)

# Latih (fit) model dengan data training (X_train dan y_train)
new_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [12]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.

# Buat prediksi pada data 'X_test' menggunakan kedua model
y_pred_dt = decision_tree_model.predict(X_test)
y_pred_new = new_model.predict(X_test)

# Tampilkan classification_report untuk Decision Tree
print("Decision Tree Performance")
print(classification_report(y_test, y_pred_dt))

print("="*50)

# Tampilkan classification_report untuk New Model
print("New Model Performance")
print(classification_report(y_test, y_pred_new))

Decision Tree Performance
              precision    recall  f1-score   support

           0       0.38      0.43      0.40        14
           1       0.43      0.35      0.39        17
           2       0.38      0.40      0.39        15

    accuracy                           0.39        46
   macro avg       0.39      0.39      0.39        46
weighted avg       0.39      0.39      0.39        46

==================================================
New Model Performance
              precision    recall  f1-score   support

           0       0.33      0.29      0.31        14
           1       0.36      0.53      0.43        17
           2       0.11      0.07      0.08        15

    accuracy                           0.30        46
   macro avg       0.27      0.29      0.27        46
weighted avg       0.27      0.30      0.28        46

In [13]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu

joblib.dump(new_model, 'explore_random_forest_classification.h5')

['explore_random_forest_classification.h5']

In [14]:
# Lakukan Hyperparameter Tuning dan Latih ulang.
# Lakukan dalam satu cell ini saja.

# Tentukan Hyperparameter yang akan di-tuning
params = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5]
}

# Buat (instantiate) objek dari algoritma tuning
#  - 'estimator': Model yang akan di-tuning
#  - 'params': Hyperparameter yang sudah kita tentukan
new_model_tuned = GridSearchCV(
    estimator = RandomForestClassifier(random_state=42),
    param_grid = params,
    cv = 5,
    scoring = 'accuracy'
)

# Latih objek model dengan data training (X_train dan y_train)
new_model_tuned.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [None, 10, 20],
                         'min_samples_split': [2, 5],
                         'n_estimators': [100, 200]},
             scoring='accuracy')

In [16]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.

# Buat prediksi pada 'X_test' Gunakan model yang sudah di-tuning
y_pred_tuning = new_model_tuned.predict(X_test)

# Tampilkan classification_report untuk model yang sudah di-tuning
print("Tuned Model Performance")
print(classification_report(y_test, y_pred_tuning))

Tuned Model Performance
              precision    recall  f1-score   support

           0       0.43      0.21      0.29        14
           1       0.32      0.59      0.42        17
           2       0.12      0.07      0.09        15

    accuracy                           0.30        46
   macro avg       0.29      0.29      0.26        46
weighted avg       0.29      0.30      0.27        46

In [17]:
# Menyimpan Model hasil tuning

joblib.dump(new_model_tuned, 'tuning_classification.h5')

['tuning_classification.h5']